# TensorFlow 基础

In [1]:
import matplotlib as mpl
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
import sklearn
import pandas as pd
import os
import sys
import time
import tensorflow as tf
from tensorflow import keras
print('tf    version: {}'.format(tf.__version__) )
print('keras version: {}'.format(keras.__version__) )

tf    version: 2.2.0-dev20200218
keras version: 2.2.4-tf


In [2]:
t = tf.constant([[1.,2.,3.], [4.,5.,6.]])
print(t)
print(t[:, 1:])

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[2. 3.]
 [5. 6.]], shape=(2, 2), dtype=float32)


In [7]:
print(t+10)
print(t @ tf.transpose(t))

Tensor("add:0", shape=(2, 3), dtype=float32)
Tensor("matmul_1:0", shape=(2, 2), dtype=float32)


In [14]:
with tf.Session() as sess:
    print(sess.run(t+10))

[[11. 12. 13.]
 [14. 15. 16.]]


In [3]:
print(t.numpy())

[[1. 2. 3.]
 [4. 5. 6.]]


In [9]:
t = tf.constant("cafe")
print(t)
print(tf.strings.length(t))
print(tf.strings.unicode_decode(t, "UTF8"))

tf.Tensor(b'cafe', shape=(), dtype=string)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor([ 99  97 102 101], shape=(4,), dtype=int32)


In [10]:
t = tf.constant(['cafe', 'coffee', '咖啡'])
print(tf.strings.length(t, unit='UTF8_CHAR'))
print(tf.strings.unicode_decode(t, "UTF8"))

tf.Tensor([4 6 2], shape=(3,), dtype=int32)
<tf.RaggedTensor [[99, 97, 102, 101], [99, 111, 102, 102, 101, 101], [21654, 21857]]>


In [14]:
r = tf.ragged.constant([[11, 12], [21, 22, 23], [], [41] ])
print(r)
print(r[1])
print(r[1:3])

<tf.RaggedTensor [[11, 12], [21, 22, 23], [], [41]]>
tf.Tensor([21 22 23], shape=(3,), dtype=int32)
<tf.RaggedTensor [[21, 22, 23], []]>


In [15]:
print(r.to_tensor())

tf.Tensor(
[[11 12  0]
 [21 22 23]
 [ 0  0  0]
 [41  0  0]], shape=(4, 3), dtype=int32)


In [18]:
s = tf.SparseTensor(indices=[[0,1], [1,0], [2,3]], 
                   values = [1. , 2, 3. ], 
                   dense_shape=[3,4])
print(s)
print(tf.sparse.to_dense(s))

SparseTensor(indices=tf.Tensor(
[[0 1]
 [1 0]
 [2 3]], shape=(3, 2), dtype=int64), values=tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))
tf.Tensor(
[[0. 1. 0. 0.]
 [2. 0. 0. 0.]
 [0. 0. 0. 3.]], shape=(3, 4), dtype=float32)


In [21]:
s = s * 2

In [22]:
print(tf.sparse.to_dense(s))

tf.Tensor(
[[0. 2. 0. 0.]
 [4. 0. 0. 0.]
 [0. 0. 0. 6.]], shape=(3, 4), dtype=float32)


In [25]:
v = tf.Variable([[1,3,2], [4,5,6]])
print(v)
print(v.value())
print(v.numpy())

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 3, 2],
       [4, 5, 6]], dtype=int32)>
tf.Tensor(
[[1 3 2]
 [4 5 6]], shape=(2, 3), dtype=int32)
[[1 3 2]
 [4 5 6]]


In [26]:
v.assign(2*v)
print(v.numpy())

[[ 2  6  4]
 [ 8 10 12]]
